//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fdevs.com.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fdevscom_apiEntities : DbContext
    {
        public fdevscom_apiEntities()
            : base("name=fdevscom_apiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIKeys> APIKeys { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ToDoItems> ToDoItems { get; set; }
        public virtual DbSet<ToDoItemDetails> ToDoItemDetails { get; set; }
    }
}
