//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fdevs.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIKeys
    {
        public int APIKeyId { get; set; }
        public System.Guid APIKey { get; set; }
        public int UserId { get; set; }
    }
}
