//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fdevs.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoItems
    {
        public int ToDoItemId { get; set; }
        public string ToDoItem { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public int UserId { get; set; }
    }
}
